version: '3.8'

services:
  etpgrf-backend:
    build: .
    # Запускаем collectstatic перед стартом сервера, чтобы обновить статику в volume
    command: sh -c "python etpgrf_site/manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 --chdir /app/etpgrf_site etpgrf_site.wsgi"
    
    volumes:
      # Монтируем папку с базой данных
      - ./data:/app/data
      # Монтируем статику в именованный том, чтобы Nginx мог её читать
      - static_volume:/app/public/static_collected
    
    env_file:
      - .env

  etpgrf-nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./config/nginx/etpgrf--internal-nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/public/static_collected
    ports:
      - "8000:80" # Слушаем 8000 снаружи, проксируем на 80 внутри
    depends_on:
      - etpgrf-backend

volumes:
  static_volume:
